services:
  3xui-shopbot:
    build: .
    restart: unless-stopped
    environment:
      SHOPBOT_SECRET_KEY: ${SHOPBOT_SECRET_KEY:-}
    ports:
      - '1488:1488'
    volumes:
      - .:/app/project
    container_name: 3xui-shopbot
